// projects/x-workbench/src/views/home/Index.vue
<template>
  <div class="home">
    <h1 class="title">Welcome!</h1>
    <Space>
      <Button type="primary" @click="workbench">编辑器</Button>
      <Button @click="renderer">渲染器</Button>
    </Space>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Button, Space } from "@arco-design/web-vue";
import { useRouter } from "vue-router";

export default defineComponent({
  components: {
    Button,
    Space
  },
  setup() {
    const router = useRouter();
    return {
      workbench() {
        router.push("/workbench");
      },
      renderer() {
        window.open("http://localhost:4000", "_blank");
      }
    };
  }
});
</script>

<style lang="less" scoped>
.home {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
  .title {
    font-size: 50px;
  }
}
</style>

// core/designer/src/pages/home/index.tsx
// import { Button, Space } from "@arco-design/web-react";
// import { Link } from "react-router-dom";
import styled from "styled-components";
import Header from "./components/Header";
import HomeMain from "./components/HomeMain";
import HomeSidebar from "./components/HomeSidebar";
const Index: React.FC = props => {
  return (
    <StyledIndex className="home">
      <Header />
      <div className="container">
        <HomeSidebar />
        <HomeMain />
      </div>
    </StyledIndex>
  );
};

const StyledIndex = styled.div`
  flex-direction: column;
  height: 100vh;
  display: flex;
  .container {
    flex: 1;
    display: flex;
    justify-content: center;
    overflow: auto;
  }
`;

export default Index;
