// packages/develop-react/src/components/arco/Button.tsx
import { Button } from "@arco-design/web-react";
import "@arco-design/web-react/es/Button/style/index";
import React, { useEffect } from "react";

const Comp: React.FC = () => {
  console.log({ useEffect });
  useEffect(() => {
    console.log(12);
  }, []);
  return <div>111</div>;
};
export default Button;

// projects/x-develop/src/components/arco/Button.vue
<script lang="tsx">
import { defineComponent } from "vue";
import { Button } from "@arco-design/web-vue";
import "@arco-design/web-vue/lib/button/style/index"

export default defineComponent({
  props: {
    name: {
      type: String,
      default: "按钮",
    },
  },
  setup(props) {
    return () => <Button>{props.name}</Button>;
  },
});
</script>
