// projects/x-workbench-vue/src/components/Header.vue
<script lang="tsx">
import { defineComponent } from "vue";
import { Button, Divider, Space } from "@arco-design/web-vue";
import { Left } from "@icon-park/vue-next";

import UserVue from "./Common/User.vue";
import PageSelector from "../views/workbench/components/PageSelector.vue";
import RouterSetterButton from "../views/workbench/components/RouterSetterButton.vue";

export default defineComponent({
  setup(props, { slots }) {
    return () => {
      return (
        <header class="header">
          <Space class="left">
            <Button shape="circle" type="text">
              <Left theme="outline" size="18" fill="#333" />
            </Button>
            <Divider direction="vertical" />
            <div class="page-selector">
              <PageSelector />
              <RouterSetterButton />
            </div>
          </Space>
          <Space class="right">
            {slots.right?.()}
            <UserVue />
          </Space>
        </header>
      );
    };
  }
});
</script>

<style lang="less" scoped>
.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  line-height: 40px;
  padding: 0 10px;
  overflow: hidden;
  background-color: var(--color-bg-2);
  color: var(--color-text-1);
  box-sizing: border-box;
  .left {
    display: flex;
    align-items: center;
    .page-selector {
      display: flex;
      align-items: center;
    }
  }
  .right {
    display: flex;
    align-items: center;
  }
}
</style>

// projects/x-designer/src/pages/designer/components/Header/index.tsx
import styled from "styled-components";
import { useRecoilValue } from "recoil";
import { Button, Divider, Select, Space } from "@arco-design/web-react";
import { IconEye, IconHistory, IconLeft, IconSave, IconSend } from "@arco-design/web-react/icon";
import { routerState } from "src/stores/routerState";
import { viewState } from "src/stores/viewState";
import RouterSetter from "../RouterSetter";
import ViewDropDown from "../ViewDropDown";

// 工作区顶栏
const WorkbenchHeader: React.FC = () => {
  const routerSchema = useRecoilValue(routerState);
  const view = useRecoilValue(viewState);
  return (
    <StyleWorkbench>
      <div className="left">
        <Button className="back-button" icon={<IconLeft />} type="text" shape="circle" />
        <Divider type="vertical" />
        <ViewDropDown />
        <RouterSetter />
      </div>
      <div className="right">
        <Button icon={<IconSave />} size="small" type="text">
          保存
        </Button>
        <Button icon={<IconHistory />} size="small" type="text">
          历史记录
        </Button>
        <Divider type="vertical" />
        <Space>
          <Button icon={<IconEye />} size="small">
            预览
          </Button>
          <Button icon={<IconSend />} size="small" type="primary">
            发布
          </Button>
        </Space>
      </div>
    </StyleWorkbench>
  );
};

const StyleWorkbench = styled.div`
  width: 100%;
  height: 40px;
  background-color: var(--color-bg-1);
  border-bottom: 1px solid var(--color-border-2);
  padding: 0 10px;
  box-sizing: border-box;

  display: flex;
  justify-content: space-between;
  align-items: center;

  .left {
    display: flex;
    align-items: center;
    .back-button {
      flex-shrink: 0;
      color: var(--color-text-1);
    }
  }
  .right {
  }
`;

export default WorkbenchHeader;
